version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always

    ports:
      - "5432:5432"
    env_file:
      - ./account.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql